### ISSUE TITLE
CGW-S-100 Impervious to Address Claim Attacks: re-work or expand to complete attack set?

### ISSUE THREAD

**Issue by BenGardiner** [nmfta-repo/vcr-experiment#6]
The CGW-S-100 Impervious to Address Claim Attacks under AGW-S-002 Prevents DoS seems like the correct rooting of the requirement and prevention of that attack is desirable. I think the presence of this single attack in the set of requirements needs to be abstracted OR we need to complete the set of attacks under CAN.

**Comment by BenGardiner** [comment]
To make matters more complicated, this is a J1939 attack, not a CAN attack per se.

**Comment by kentindell** [comment]
If I understand correctly, the address claim attack uses a CAN protocol attack, which can't take place through a security gateway. So it might be better to re-word this requirement as "Prevent CAN protocol attacks", cite something that talks about the address claim attack / CAN protocol attacks. I could pull together some words on this if I can get a definitive description of the address claim attack.

**Comment by BenGardiner** [comment]
@kentindell thank you, I agree with your stated understanding. Could you review the changes proposed in https://github.com/nmfta-repo/vcr-experiment/pull/27 ?
